import {
  Leaf,
  User,
  Settings,
  Home,
  BarChart,
  DollarSign,
  Activity,
  Briefcase,
  ShoppingCart,
  CreditCard,
  Bell,
  Calendar,
  Camera,
  Cloud,
  Code,
  Database,
  Download,
  Upload,
  Eye,
  Heart,
  Lock,
  Mail,
  MapPin,
  MessageCircle,
  Phone,
  Search,
  Shield,
  Star,
  Trash,
  TrendingUp
} from "lucide-react";

export const ICONS = [
  { name: "Leaf", icon: Leaf },
  { name: "User", icon: User },
  { name: "Settings", icon: Settings },
  { name: "Home", icon: Home },
  { name: "BarChart", icon: BarChart },
  { name: "DollarSign", icon: DollarSign },
  { name: "Activity", icon: Activity },
  { name: "Briefcase", icon: Briefcase },
  { name: "ShoppingCart", icon: ShoppingCart },
  { name: "CreditCard", icon: CreditCard },
  { name: "Bell", icon: Bell },
  { name: "Calendar", icon: Calendar },
  { name: "Camera", icon: Camera },
  { name: "Cloud", icon: Cloud },
  { name: "Code", icon: Code },
  { name: "Database", icon: Database },
  { name: "Download", icon: Download },
  { name: "Upload", icon: Upload },
  { name: "Eye", icon: Eye },
  { name: "Heart", icon: Heart },
  { name: "Lock", icon: Lock },
  { name: "Mail", icon: Mail },
  { name: "MapPin", icon: MapPin },
  { name: "MessageCircle", icon: MessageCircle },
  { name: "Phone", icon: Phone },
  { name: "Search", icon: Search },
  { name: "Shield", icon: Shield },
  { name: "Star", icon: Star },
  { name: "Trash", icon: Trash },
  { name: "TrendingUp", icon: TrendingUp },
];